# Generated by Django 6.1 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_conversation_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="publicaciones/%Y/%m/", verbose_name="Foto"),
        ),
    ]
