# Generated by Django 6.1 on 2026-08-26 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_publication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='availability',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='publication',
            name='currency',
            field=models.CharField(default='mxn', max_length=3),
        ),
        migrations.AddField(
            model_name='publication',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_status',
            field=models.CharField(choices=[('no_configurada', 'No configurada'), ('pendiente', 'Pendiente'), ('configurada', 'Configurada'), ('restringida', 'Restringida')], default='no_configurada', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('archivada', 'Archivada')], default='activa', max_length=10),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('status', models.CharField(choices=[('propuesta', 'Propuesta'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('pagado', 'Pagado'), ('en_proceso', 'En proceso'), ('completado', 'Completado')], default='propuesta', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='accounts.conversation')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='accounts.publication')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lux_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pago_iniciado', 'Pago iniciado'), ('pagado', 'Pagado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=16)),
                ('external_payment_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='accounts.agreement')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.publication')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraude', 'Fraude'), ('inapropiado', 'Inapropiado'), ('enganosa', 'Enganosa'), ('incumplimiento', 'Incumplimiento'), ('spam', 'Spam'), ('evasión', 'Evasión'), ('otro', 'Otro')], max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisando', 'Revisando'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente', max_length=12)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.agreement')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.message')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_moderated', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.publication')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Advertencia'), (2, 'Advertencia formal'), (3, 'Última advertencia'), (4, 'Suspensión')])),
                ('evidence_reference', models.CharField(blank=True, max_length=200)),
                ('is_serious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warnings_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounts.transaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transaction', 'author'), name='one_review_per_transaction_author')],
            },
        ),
    ]
